[package]
name = "hctl"
version = "0.2.0"
edition = "2021"
authors = [ "Michał Szmidt" ]
repository = "https://github.com/michalszmidt/hctl"
license-file = "LICENSE"
keywords = ["pi-hole hostfile", "adguardhome", "hostlist", "adguard-home", "hostfiles", "dns-blocking", "dns-blocklists", "adguard-dns" ]
categories = ["command-line-utilities"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "*"                                             # Apache 2.0 / MIT
regex = "*"                                             # Apache 2.0 / MIT
itertools = "*"                                         # Apache 2.0 / MIT
clap = { version="*", features = ["default"] }          # Apache 2.0 / MIT
serde = { vesrion="1.0.180", features = ["derive"] }       
serde_yaml = "*"                               
minreq = { version="*", features = ["https-native"] }   # MIT
indicatif = "*"                                         # MIT
# delegate = "*"                                          # Apache 2.0 / MIT
# url = "*"