name: Publish for OpenBSD amd64

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: macos-12
    name: Build for OpenBSD
    steps:
    - uses: actions/checkout@v3
    - name: Compile in OpenBSD VM
      id: test
      uses: vmactions/openbsd-vm@v0
      with:
        usesh: false
        mem: 8192
        prepare: |
          pkg_add curl rust pkgconf openssl

        run: |
          ls -lah
          rustc --version
          cargo build --release
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl
        asset_name: hctl-openbsd-amd64
        tag: ${{ github.ref }}