name: Publish for FreeBSD

on:
  push:
    tags:
      - '*'

jobs:
  build_freebsd:
    runs-on: macos-12
    name: Build for FreeBSD-RELEASE
    steps:
    - uses: actions/checkout@v3
    - name: Compile in FreeBSD VM
      id: compile
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: false
        mem: 2048
        prepare: |
          mkdir -p /usr/local/etc/pkg/repos
          cp /etc/pkg/FreeBSD.conf /usr/local/etc/pkg/repos
          sed -i 's/FreeBSD:/FreeBSDlatest:/g'
          echo "FreeBSD: { enabled: no }" > /usr/local/etc/pkg/repos/FreeBSD.conf
          pkg update
          pkg upgrade -y
          pkg install -y curl rust pkgconf openssl
          rehash

        run: |
          rehash
          ls -lah
          rustc --version
          cargo build --release
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/hctl
        asset_name: hctl-freebsd-amd64
        tag: ${{ github.ref }}